pipeline {
    environment {
        testingregistry = "knoxie2/products_api_testing"
        productionregistry = "knoxie2/products_api"
        registryCredential = 'knoxie2'
        dockerImage = ''
        HOME = '/tmp'

    }

    agent any

    stages {
        stage('Development: Building Development image for Unit Tests') {
          when {
              branch 'development'
            }
            steps {
              script {
                dockerImage = docker.build testingregistry + ":latest"
              }
            }
        }
        
        stage('Development: Running Unit Tests') {
          when {
              branch 'development'
            }
            steps {
              script {
                docker.image("knoxie2/products_api_testing:latest").inside("""--entrypoint=''""") {
                  sh 'dotnet --version'
                  sh 'cd src/ProductsApi.Unittests'
                  sh 'dotnet test --logger "trx;LogFileName=unit_tests.xml"'
                }
              }
            }
        }
        
        stage('Staging: Building image for Staging') {
          when {
              branch 'staging'
            }
            steps {
              script {
                 dockerImage = docker.build(testingregistry + ":${env.BUILD_ID}") 
              }
            }
        }
        
        stage('Main: Building image for Production') {
          when {
              branch 'main'
            }
            steps {
              script {
                 dockerImage = docker.build(testingregistry + ":${env.BUILD_ID}") 
              }
            }
        }

        stage('Push image to Ducker Hub') {
           when {
               not {
                branch 'development'
              }
            }
            steps{    
              script {
                docker.withRegistry( '', registryCredential ) {
                  // dockerImage.push("${env.BUILD_ID}")
                  dockerImage.push("latest")
                }
              }
            }
        }

        stage('Development: Remove Unused Development docker image') {
           when {
              branch 'development'
            }
            steps{
              sh "docker rmi $testingregistry:${env.BUILD_ID}" 
            }
        }

        stage('Staging: Remove Unused Production docker image') {
           when {
              branch 'staging'
            }
            steps{
              sh "docker rmi $testingregistry:${env.BUILD_ID}"
            }
        }
      
        stage('Main: Remove Unused Production docker image') {
           when {
              branch 'main'
            }
            steps{
              sh "docker rmi $productionregistry:${env.BUILD_ID}"
            }
        }

        stage('Deploy to Staging environment') {
          when {
              branch 'staging'
            }
            steps{
              ansiblePlaybook(credentialsId: 'swarm-manager', playbook: './deployment/playbooks/deploy-for-staging.yml',inventory: "${HOSTS}")
            }
        }

        stage('Deploy to Production environment') {
          when {
              branch 'main'
            }
            steps{
              ansiblePlaybook(credentialsId: 'swarm-manager', playbook: './deployment/playbooks/deploy-for-production.yml',inventory: "${HOSTS}")
            }
        }
      
        stage('CleanWorkspace') {
            steps {
                cleanWs()
            }
        }
      
    }
}
